# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
