# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_label_project'),
        ('contacts', '0003_auto_20170202_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='role',
        ),
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.ManyToManyField(blank=True, to='utils.Label'),
        ),
    ]
