# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170116_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tester',
            name='avatar',
            field=models.FileField(blank=True, default='/static/images/avatar_default.png', null=True, upload_to=users.models.user_directory_path),
        ),
    ]
