# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_context_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Context'),
        ),
    ]
