# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_tester_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='tt_date_range_end',
            field=models.DateField(default=users.models.week_from_now),
        ),
    ]
