# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170207_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='tt_search_bar',
            field=models.CharField(default="''", max_length=50),
        ),
    ]
