# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170211_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
