# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170302_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
