# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-13 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_entry',
            name='ancestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetracker.Time_Entry'),
        ),
        migrations.AddField(
            model_name='time_entry',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='time_entry',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_timetracker', to='timetracker.Time_Entry'),
        ),
        migrations.AddField(
            model_name='time_entry',
            name='newest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='time_entry',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
