# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_auto_20170116_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=260, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='time_object',
            options={},
        ),
        migrations.AlterModelOptions(
            name='variable_item',
            options={},
        ),
    ]
