# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20170126_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='project',
            field=models.BooleanField(default=False),
        ),
    ]
