# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import files.file_utils


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_label_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='supporting_file',
            field=models.FileField(blank=True, null=True, upload_to=files.file_utils.feedback_file_path),
        ),
    ]
