# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_auto_20170411_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='ri_label',
            field=models.BooleanField(default=False),
        ),
    ]
