# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 09:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_auto_20170530_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
