# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 14:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_label_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='attr_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
