# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tier', models.IntegerField(default=1)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('command', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('automate', models.BooleanField(default=False)),
                ('mangle', models.CharField(blank=True, max_length=50)),
                ('help_base', models.TextField(blank=True, null=True)),
                ('help_import', models.TextField(blank=True, null=True)),
                ('est_time', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sequence', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('shorthand', models.CharField(max_length=10)),
                ('phase', models.ManyToManyField(blank=True, to='methodologies.Phase')),
            ],
        ),
        migrations.AddField(
            model_name='method',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='methodologies.Phase'),
        ),
        migrations.AddField(
            model_name='method',
            name='project_type',
            field=models.ManyToManyField(blank=True, to='methodologies.Project_Type'),
        ),
    ]
