# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20161227_0946'),
        ('methodologies', '0002_method_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
