# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0006_auto_20170103_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='version',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='phase',
            name='guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='version',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='project_type',
            name='guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='project_type',
            name='version',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
