# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0009_auto_20170310_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
    ]
