# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0014_auto_20170310_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='ancestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='methodologies.Method'),
        ),
        migrations.AddField(
            model_name='method',
            name='descendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='method_descendant', to='methodologies.Method'),
        ),
        migrations.AddField(
            model_name='method',
            name='newest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='method',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
    ]
