# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('methodologies', '0015_auto_20170310_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='suggestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
