# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0016_method_suggestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='parent_guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
