# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_guid'),
        ('methodologies', '0017_method_parent_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='children',
            field=models.ManyToManyField(blank=True, to='tasks.Task'),
        ),
    ]
