# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0018_method_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='mangle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
