# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0019_auto_20170512_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='lineage_guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
