# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0020_method_lineage_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='lineage_guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
