# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-20 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0024_auto_20180717_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_type',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
    ]
