# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170116_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_date_range_start', models.DateField(default=django.utils.timezone.now)),
                ('tt_date_range_end', models.DateField(default=django.utils.timezone.now)),
                ('tt_fields_sort_by', models.CharField(default='-date', max_length=50)),
                ('tt_search_bar', models.CharField(default='', max_length=50)),
                ('tt_user_filter', models.CharField(default='all', max_length=50)),
                ('tt_project_filter', models.CharField(default='all', max_length=50)),
                ('pulse_state', models.CharField(default='collapse', max_length=50)),
                ('pulse_btn_class', models.CharField(default='fa-plus', max_length=50)),
                ('pulse_body_style', models.CharField(default='display:none;', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remember_me', models.BooleanField(default=False)),
            ],
        ),
    ]
