# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_tester_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='review',
            field=models.BooleanField(default=False),
        ),
    ]
