# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-22 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_tester_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='ms_date_range_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='ms_date_range_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='ms_project_filter',
            field=models.CharField(default='all', max_length=50),
        ),
        migrations.AddField(
            model_name='context',
            name='ms_sort_ascending',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='context',
            name='ms_sort_field',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='context',
            name='ms_status_filter',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
