# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 03:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client_issue_designation', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('issue_number', models.PositiveIntegerField(default=1)),
                ('daily_version', models.PositiveIntegerField(default=1)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('associated_files', models.ManyToManyField(blank=True, to='files.Associated_File')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('contributors', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('issue_files', models.ManyToManyField(blank=True, to='files.Issue_File')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issuetracker.Status'),
        ),
        migrations.AddField(
            model_name='issue',
            name='technical_poc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_poc', to=settings.AUTH_USER_MODEL),
        ),
    ]
