# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0002_auto_20170302_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issuetracker.Status'),
        ),
    ]
