# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0005_auto_20170103_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='sequence',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
