# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0007_auto_20170125_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='parent_guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
