# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0008_phase_parent_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='ancestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='methodologies.Phase'),
        ),
        migrations.AddField(
            model_name='phase',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childphase', to='methodologies.Phase'),
        ),
    ]
