# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0011_phase_suggestor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='child',
            new_name='descendant',
        ),
        migrations.AddField(
            model_name='phase',
            name='newest',
            field=models.BooleanField(default=True),
        ),
    ]
