# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0021_phase_lineage_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
