# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0022_auto_20170524_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_type',
            name='lineage_guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='project_type',
            name='newest',
            field=models.BooleanField(default=True),
        ),
    ]
