# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0023_auto_20170608_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
