# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20170412_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repor_Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.TextField(blank=True, null=True)),
                ('template', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('limit', models.PositiveIntegerField(default=1000)),
            ],
        ),
    ]
