# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 20:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0005_repor_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.TextField(blank=True, null=True)),
                ('template', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('limit', models.PositiveIntegerField(default=1000)),
                ('input_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wizard_Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=260, null=True)),
                ('lineage_guid', models.CharField(blank=True, max_length=260, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('variables', models.ManyToManyField(to='reports.Report_Variable')),
            ],
        ),
        migrations.CreateModel(
            name='Wizard_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=260, null=True)),
                ('lineage_guid', models.CharField(blank=True, max_length=260, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('steps', models.ManyToManyField(to='reports.Wizard_Step')),
            ],
        ),
        migrations.DeleteModel(
            name='Repor_Variable',
        ),
    ]
