# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20170524_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizard_template',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wizard_template',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
