# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_wizard_step_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizard_step',
            name='title',
            field=models.CharField(blank=True, default='New Wizard', max_length=100, null=True),
        ),
    ]
