# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20170526_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_variable',
            name='display',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
