# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20170527_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizard_step',
            name='items',
            field=models.ManyToManyField(blank=True, to='reports.Report_Item'),
        ),
    ]
