# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20170530_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizard_variable',
            name='template_var',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
