# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_wizard_variable_template_var'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizard_variable',
            name='limited',
            field=models.BooleanField(default=False),
        ),
    ]
