# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 18:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20170410_0958'),
        ('reports', '0020_auto_20170530_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizard_template',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.Associated_File'),
        ),
        migrations.AlterField(
            model_name='wizard_template',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
