# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 11:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_report_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='template_context',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
