# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 11:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_report_template_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variables', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25, null=True), size=None), size=None)),
            ],
        ),
    ]
