# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 11:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_variable_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable_list',
            name='variables',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), size=None),
        ),
    ]
