# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0031_auto_20170608_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
