# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 09:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0034_auto_20170622_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_item',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
