# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 22:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0036_remove_report_item_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_item',
            name='attrs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
