# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 15:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0038_auto_20170912_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_item',
            name='attrs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{"Title":""}'),
        ),
    ]
