# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-12 02:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0041_report_step_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_item',
            name='attrs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'Title': [{'input_type': 'text', 'value': ''}]}),
        ),
    ]
