# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-08 00:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0043_static_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Item_Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('input_type', models.CharField(default='text', max_length=20)),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('selected', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Report_Item_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='report_item',
            name='attrs',
        ),
        migrations.AlterField(
            model_name='report_item',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Report_Item_Type'),
        ),
        migrations.AddField(
            model_name='report_item_attribute',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='reports.Report_Item'),
        ),
        migrations.AddField(
            model_name='report_item_attribute',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='reports.Report_Item_Type'),
        ),
    ]
