# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-08 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0044_auto_20180808_0040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variable_List',
        ),
        migrations.RemoveField(
            model_name='report',
            name='template_context',
        ),
        migrations.RemoveField(
            model_name='report',
            name='variables',
        ),
        migrations.RemoveField(
            model_name='wizard_step',
            name='variables',
        ),
        migrations.RemoveField(
            model_name='wizard_template',
            name='steps',
        ),
        migrations.AddField(
            model_name='wizard_step',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='reports.Report'),
        ),
        migrations.AddField(
            model_name='wizard_step',
            name='wizard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='reports.Wizard_Template'),
        ),
        migrations.AddField(
            model_name='wizard_variable',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='reports.Wizard_Step'),
        ),
    ]
