# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 21:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scratchpad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('in_use', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('testers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='current_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
