# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20161224_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
