# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20170307_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='newest',
            field=models.BooleanField(default=False),
        ),
    ]
