# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_note_newest'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_note', to='notes.Note'),
        ),
    ]
