# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-14 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_narrative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='time',
        ),
        migrations.RemoveField(
            model_name='note',
            name='time_entry',
        ),
    ]
