# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20170216_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
