# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '0010_auto_20170216_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
