# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20170216_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
