# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20170811_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='status',
            field=models.CharField(blank=True, default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='completion_milestone', to='project.Milestone'),
        ),
    ]
