# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20170524_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizard_step',
            name='variables',
            field=models.ManyToManyField(blank=True, to='reports.Report_Variable'),
        ),
        migrations.AlterField(
            model_name='wizard_template',
            name='steps',
            field=models.ManyToManyField(blank=True, to='reports.Wizard_Step'),
        ),
    ]
