# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_wizard_variable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizard_step',
            name='items',
        ),
        migrations.AlterField(
            model_name='wizard_step',
            name='variables',
            field=models.ManyToManyField(blank=True, to='reports.Wizard_Variable'),
        ),
    ]
