# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_wizard_variable_limited'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizard_variable',
            name='selectable',
            field=models.BooleanField(default=False),
        ),
    ]
