# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_auto_20170602_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_item',
        ),
        migrations.AddField(
            model_name='report',
            name='guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='lineage_guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='wizard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Wizard_Template'),
        ),
    ]
