# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_auto_20170606_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='variables',
            field=models.ManyToManyField(blank=True, to='reports.Wizard_Variable'),
        ),
    ]
