# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 12:52
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_auto_20170607_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizard_variable',
            name='selected',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=[], size=None),
            preserve_default=False,
        ),
    ]
