# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_auto_20170607_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='wizard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Wizard_Template'),
        ),
    ]
