# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 07:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0032_auto_20170622_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizard_variable',
            name='selected',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), blank=True, null=True, size=None),
        ),
    ]
