# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0035_report_item_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_item',
            name='attributes',
        ),
    ]
