# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0037_report_item_attrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_item',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
