# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-18 02:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0039_auto_20171003_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_item',
            name='attrs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'Title': ''}),
        ),
    ]
