# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-03 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0040_auto_20180518_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='step_modified',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
