# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('methodologies', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.BooleanField(default=False)),
                ('sequence', models.IntegerField(default=1)),
                ('tier', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('help_base', models.CharField(blank=True, default='', max_length=1000)),
                ('base_command', models.CharField(blank=True, default='', max_length=3500)),
                ('est_time', models.CharField(blank=True, default='', max_length=12)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tsk_duration', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('exec_duration', models.CharField(blank=True, default='', max_length=50)),
                ('exec_cmd', models.TextField(blank=True, default='', max_length=3500)),
                ('meth_item', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='methodologies.Method')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='methodologies.Phase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('session_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Time_Object')),
                ('variables', models.ManyToManyField(blank=True, to='utils.Variable_Item')),
            ],
        ),
    ]
