# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20170116_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent_guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
