# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('methodologies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('codename', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('issue_number', models.PositiveIntegerField(blank=True, default=1)),
                ('is_billable', models.BooleanField(default=True)),
                ('project_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='methodologies.Project_Type')),
            ],
            options={
                'ordering': ('end_date',),
            },
        ),
    ]
