# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20170122_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
