# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('utils', '0006_auto_20170126_1529'),
        ('project', '0006_auto_20170125_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=260, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Label')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='vips',
            field=models.ManyToManyField(blank=True, to='project.Vip'),
        ),
    ]
