# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=260, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='milestones',
            field=models.ManyToManyField(blank=True, to='project.Milestone'),
        ),
    ]
