# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0007_auto_20170125_1344'),
        ('tasks', '0003_auto_20170116_1806'),
        ('project', '0011_auto_20170216_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='milestones',
        ),
        migrations.AddField(
            model_name='milestone',
            name='phases',
            field=models.ManyToManyField(blank=True, to='methodologies.Phase'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='tasks.Task'),
        ),
    ]
