# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_project_project_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
