# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20161227_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='associated_file',
            name='guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='issue_file',
            name='guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
