# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20170409_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associated_file',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
    ]
