# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20170410_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='associated_file',
            name='lineage_guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='associated_file',
            name='newest',
            field=models.BooleanField(default=True),
        ),
    ]
