# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20170811_1041'),
        ('datatables', '0002_auto_20170928_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatable',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project'),
        ),
    ]
