# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0004_datatype_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataitem',
            name='guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='datatable',
            name='guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
