# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_time_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ancestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
