# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0003_datatable_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
