# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.file_utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0002_auto_20161218_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('current_page', models.URLField(max_length=1000)),
                ('supporting_file', models.FileField(blank=True, null=True, upload_to=files.file_utils.feedback_file_path)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='meth_item',
            name='files',
        ),
        migrations.RemoveField(
            model_name='meth_item',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='meth_item',
            name='project_type',
        ),
        migrations.DeleteModel(
            name='Meth_Item',
        ),
    ]
