# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_label_ri_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
