# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_auto_20170412_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='lineage_guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
