# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 14:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_label_attr_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='attr_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
