# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-17 03:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_auto_20171003_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'Title': ''}),
        ),
    ]
