# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-12 02:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0017_auto_20180517_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'Title': [{'input_type': 'text', 'value': ''}]}),
        ),
    ]
