# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_mangle'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
