# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-30 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20170524_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='est_time',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
