# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('files', '0002_remove_issue_file_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_file',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='issue_file',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
