# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20170125_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='associated_file',
            name='a_i_guid',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
