# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import files.file_utils


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_associated_file_a_i_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associated_file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=files.file_utils.project_directory_path),
        ),
        migrations.AlterField(
            model_name='issue_file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=files.file_utils.issue_file_path),
        ),
    ]
